### ISSUE TITLE
Any script example ?

### ISSUE THREAD

**Issue by shiglet** [salesprendes/Bot-Dofus-1.29.1#12]
Do you have some script examples ?

**Comment by odreal** [comment]
I think there is some example in the trayectos folder.
By the way, I used your fork but there is a problem with the movement system when I enter in the combat mode, am I alone to have this problem ?
`Error desplazando el personaje a la casilla: XXX`

**Comment by shiglet** [comment]
> I think there is some example in the trayectos folder.
> By the way, I used your fork but there is a problem with the movement system when I enter in the combat mode, am I alone to have this problem ?
> `Error desplazando el personaje a la casilla: XXX`

Yeah i found it ! Thank you.

I didn't test the combat system yet. I will try it maybe tomorrow .

**Comment by disnaas** [comment]
I think I'll add autopath in my range and review the system in combat because it's not great

**Comment by shiglet** [comment]
Thank you :) 

> I think I'll add autopath in my range and review the system in combat because it's not great

What do you mean by autopath ? 

Yep the combat system isn't that great, it's fucking slow lol
